server:
  port: 8001
spring:
  h2:
    console:
      enabled: true
  application:
    name: hr-payroll

eureka:
  client:
    register-with-eureka:
      fetch-registry:
      service-url:
        defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost