server:
  port: 8004
spring:
  h2:
    console:
      enabled: true
  application:
    name: hr-oauth

eureka:
  client:
    register-with-eureka:
      fetch-registry:
      service-url:
        defaultZone: http://hr-eureka-server:8761/eureka/
  instance:
    hostname: localhost